format_version: 10
pipelines:
  expense-tf-Plan:
    group: expenseTerraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-214f6fa:
        git: https://github.com/cDevOps78/expense_terraformGoCD.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          secure_variables:
            VAULT_TOKEN: "AES:/jvkC1Lso4gftkDu9XOmEg==:N8TCA8tmeOrSSuPA10zqTTvLhGmOI+Ut6sCe4jBH6BQ="
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            job1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                      - dev
                      - plan
                    command: bash
                    run_if: passed